### ISSUE TITLE
Bad notification posted from package Name: Couldn't create icon StatusBarIcon (Resource ID :id=0x7f08013b)

### ISSUE THREAD

**Issue by rnjt-sp6** [hypertrack/sdk-android#5]
**Description:**
We facing a huge amount of fatal exceptions per day after updating the build to latest hypertrack sdk 5.4.3. It is happening on some devices like Samsung, RealMe(Android 11). Sharing the details below.

**Environment**
Android compile and target sdk: 30
Hypertrack version: 'com.hypertrack:hypertrack:5.4.3'

**Crashlog from crashlytics**
Fatal Exception: android.app.RemoteServiceException: Bad notification(tag=null, id=101010) posted from package net.loadshare.atlas.b2c.beta, crashing app(uid=10393, pid=18275): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE Package name id=0x7f08013b) visible user=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2250)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
       
**Crashlog from debugging the issue**
E/Icon: Unable to load resource 0x7f08013b from $PackageName
android.content.res.Resource$NotFoundException: Drawable PackageName:drawable/ic_hypertrack_notification with resource ID #0x7f08013b
Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1

Checked the hypertrack sdk code on ic_hypertrack_notification, It is there as vector drawable
Kindly fix it or suggest some way to override this icon from our codebase.

**Comment by pavel-kuznetsov-hypertrack** [comment]
Thank you for you'r bugreport. This issue is resolved in SDK 5.4.4

**Comment by rnjt-sp6** [comment]
> Thank you for you'r bugreport. This issue is resolved in SDK 5.4.4

Thanks @pavel-kuznetsov-hypertrack
